curvefi/curve-api

utils/data/tokens-prices.js
Will be followed up by an update to look at the dynamic discount
=> Fix rkpr price

pages/api/getTVLOptimism.js
=> Add new tvl endpoint

constants/configs.js, pages/api/getFactoryV2Pools/index.js, utils/Calls.js
- Add automatic bisecting of reverting call in dev for multiCall util
- Add way to ignore broken pools
- Remove broken pools on polygon factory
=> Remove broken pools on polygon factory and add utilities for quick debugging of reverting calls in multicall

pages/api/getFactoryV2Pools/index.js
Due to this mismatch some data wasn't matched to the right pool, hence some pools were missing data such as coin metadata
=> Fix facto pool internal index mismatch

pages/api/getFactoryAPYs.js
For new pools, weekly would obviously not be retrievable (revert), and 
it'd take down the daily measurements with it; this fixes it
=> Fetch crypto pools weekly apy separately from daily for resilience

pages/api/getGauges.js
lp token for this pool can be confirmed here: https://ftmscan.com/address/0x0fa949783947Bf6c1b171DB13AEACBB488845B3f#readContract
=> fix: geist pool lp token

pages/api/getPools/index.js
Use balances() method on pool contracts to retrieve underlying balances 
in a more reliable way
=> Retrieve actual eth balances for crypto pools listing weth as underlying yet using native eth

pages/api/getGauges.js, pages/api/getPoolList/index.js, utils/Array.js
- Add pusd/3crv and ohm/eth gauges
- Filter out zero address from registries addresses to prevent getPoolList from throwing
=> Tweaks to getGauges and getPoolList

pages/api/getGauges.js
https://gov.curve.fi/t/proposal-to-remove-ust-pool-gauges/3939
=> Mark ust gauges as killed

constants/configs.js, pages/api/getFactoryAPYs-arbitrum.js, pages/api/getFactoryAPYs-avalanche.js, pages/api/getFactoryAPYs-fantom.js, pages/api/getFactoryAPYs-polygon.js, pages/api/getFactoryAPYs/_sidechains.js, pages/api/getPools/index.js
Goes with https://github.com/curvefi/curve-ui-private/pull/463
=> Add crypto facto pools support to ftm & poly

pages/api/getPools/index.js
> on sidechain factory pools, pool.balances(1) === gauge.balanceOf(pool)
> on mainnet factory pools, pool.balances(1) === lp.balanceOf(pool)
=> Fix double-counting sidechain factory meta pools' base pool balance

constants/configs.js
Goes with https://github.com/curvefi/curve-ui-private/pull/483
=> Add fraxusdc to choice of base pools

pages/api/getGauges.js
=> Revert "Update getGauges.js"

pages/api/getPools/index.js
Only for Avalanche factory for now, while we properly test expanding to 
more chains
=> Decrease reliance on gecko prices w/e price can be derived from curve

README.md, package-lock.json, package.json, pages/api/getPools/_utils.js, pages/api/getPools/index.js
F/u to #214
(For future reference) Regression testing done manually by querying the live endpoint and storing its output in `var A`, and storing in `var B` the output of the local dev endpoint, and then running the rough-around-the-edges code below to detect any significant differences in usd prices between both versions, to manually confirm the new, local value is a more accurate value than the previous:
```js
A.data.poolData.filter(({ address, coins, usdTotal }) => {
const poolB = B.data.poolData.find(({ address: addressB }) => addressB.toLowerCase() === address.toLowerCase());
if (usdTotal < 10 && poolB.usdTotal < 10) return false;
const coinsB = poolB.coins;
const differences = coins.map(({ usdPrice }, i) => (
(usdPrice === null && coinsB[i].usdPrice === null) ? 1 :
usdPrice / …
```
=> Expand the use of curve prices for factory pools to all chains

constants/configs.js
Goes with https://github.com/curvefi/curve-ui-private/pull/507
=> Add fraxbp as base pool on arbitrum & optimism

constants/CoinAddressCoingeckoIdMap.js, pages/api/getMainRegistryPoolsAndLpTokens.js, pages/api/getPools/_utils.js, pages/api/getPools/index.js, utils/Calls.js
=> Derive most prices from curve pools

constants/Web3.js, pages/api/getAllGauges.js, pages/api/getCoins.js, pages/api/getFactoryAPYs/ethereum.js, pages/api/getGauges.js, pages/api/getPools/index.js
=> Move all to llamanodes

pages/api/getPools/index.js
(the appropriate balance being a fraction of the underlying pool's own  tokens balances)
=> Set appropriate balance for meta pools underlying tokens

constants/configs/configs.js
Celo subgraphs not picking up pools atm, it will as soon as factory registry is added to the address provider there (will be done very soon)
=> Add aurora & celo subgraphs
